flags: {}
packages:
- '.'

- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 1f9c923a4d55ea700aa98a83d99836a3c419385b
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: 5ebefbadeefa99e35e97d558f93f2597c0c85b09
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 2d009482512b321cf511834bf9071f93d7465780
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: 27a23e33d00552821141cf2a46654df7ec4559b5
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- multiset-0.2.2
- term-rewriting-0.2
- union-find-array-0.1.0.2
resolver: lts-2.22
