flags:
  transformers-compat:
    five-three: true
packages:
- .
- ../term-rewriting-xml
- ../term-rewriting-applicative
- ../term-rewriting-ext
- ../term-rewriting
- ../slogic
- ../tct-core
- ../tct-common
- ../ara
- ../hoca
- ../union-find-array
extra-deps:
- fgl-visualize-0.1.0.1@sha256:e682066053a6e75478a08fd6822dd0143a3b8ea23244bdb01dd389a266447c5e,995

resolver: lts-14.8
# resolver: lts-13.20 # ghc-8.6.5
