flags: {}
packages:
- '.'

- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 54beea4baf8f2ad1f02d86b4319512b6e70ab4a2
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: d535bce1db3ea4c76df3aa202bcac441365ece2b
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: cfe3ad6b9062c2fdf397734d69c263920f99165e
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: b88ce5394cb9a7dde6d3a08a0a15391991e36ed5
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- multiset-0.2.2
- term-rewriting-0.2
- union-find-array-0.1.0.2
resolver: lts-3.4
