flags:
  transformers-compat:
    five-three: true
packages:
- .
- ../term-rewriting-xml
- ../term-rewriting-applicative
- ../term-rewriting-ext
- ../slogic
- ../tct-core
- ../tct-common
- ../ara
- ../hoca
extra-deps:
- List-0.6.2
- QuickCheck-2.11.3
- StateVar-1.1.1.0
- adjunctions-4.4
- ansi-terminal-0.8.0.4
- ansi-wl-pprint-0.6.8.2
- async-2.2.1
- base-compat-0.10.4
- base-orphans-0.8
- bifunctors-5.5.3
- cabal-doctest-1.0.6
- call-stack-0.1.0
- cmdargs-0.10.20
- colour-2.3.4
- comonad-5.0.4
- contravariant-1.5
- distributive-0.6
- dlist-0.8.0.4
- dotgen-0.4.2
- exceptions-0.10.0
- fgl-5.5.3.1
- fgl-visualize-0.1.0.1
- free-5.1
- graphviz-2999.20.0.2
- hashable-1.2.7.0
- hexpat-0.20.13
- invariant-0.5.1
- kan-extensions-5.2
- lens-4.17
- monad-parallel-0.7.2.3
- multiset-0.3.4
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.2.0
- parallel-3.2.2.0
- polyparse-1.12
- primitive-0.6.4.0
- profunctors-5.3
- random-1.1
- reflection-2.1.4
- semigroupoids-5.3.1
- semigroups-0.18.5
- tagged-0.8.6
- temporary-1.2.0.4
- term-rewriting-0.2.1.1
- tf-random-0.5
- th-abstraction-0.2.8.0
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
- union-find-array-0.1.0.2
- unordered-containers-0.2.9.0
- utf8-string-1.0.1.1
- vector-0.12.0.1
- void-0.7.2
- wl-pprint-text-1.2.0.0
resolver: ghc-8.4.1
